export const quotes = [
  { id: 1, text: "La disciplina è il ponte tra gli obiettivi e i risultati.", author: "Jim Rohn" },
  { id: 2, text: "Non contare i giorni, fai in modo che i giorni contino.", author: "Muhammad Ali" },
  { id: 3, text: "Il successo non è definitivo, il fallimento non è fatale: è il coraggio di continuare che conta.", author: "Winston Churchill" },
  { id: 4, text: "Le abitudini sono le fondamenta su cui costruiamo la nostra vita.", author: "Aristotele" },
  { id: 5, text: "Ogni grande viaggio inizia con un singolo passo.", author: "Lao Tzu" },
  { id: 6, text: "Non aspettare. Il momento giusto non arriverà mai.", author: "Napoleon Hill" },
  { id: 7, text: "La costanza è ciò che trasforma la mediocrità in eccellenza.", author: "Anonimo" },
  { id: 8, text: "Fai oggi ciò che gli altri non vogliono fare, e domani avrai ciò che gli altri non possono avere.", author: "Jerry Rice" },
  { id: 9, text: "Il dolore di oggi è la forza di domani.", author: "Anonimo" },
  { id: 10, text: "Non si tratta di avere tempo, si tratta di fare tempo.", author: "Anonimo" },
  { id: 11, text: "La motivazione ti fa iniziare. L'abitudine ti fa continuare.", author: "Jim Ryun" },
  { id: 12, text: "Ogni mattina abbiamo due scelte: continuare a dormire con i nostri sogni, o svegliarci e inseguirli.", author: "Anonimo" },
  { id: 13, text: "Il modo in cui trascorri i tuoi giorni è il modo in cui trascorri la tua vita.", author: "Annie Dillard" },
  { id: 14, text: "Non cercare di essere migliore degli altri. Cerca di essere migliore di te stesso.", author: "William Faulkner" },
  { id: 15, text: "I piccoli progressi quotidiani portano a grandi risultati.", author: "Anonimo" },
  { id: 16, text: "La vita è 10% ciò che ti accade e 90% come reagisci.", author: "Charles Swindoll" },
  { id: 17, text: "Non smettere mai finché non sei orgoglioso.", author: "Anonimo" },
  { id: 18, text: "Il segreto per andare avanti è cominciare.", author: "Mark Twain" },
  { id: 19, text: "Sii la versione migliore di te stesso, non una copia mediocre di qualcun altro.", author: "Judy Garland" },
  { id: 20, text: "La forza non viene dalla capacità fisica. Viene dalla volontà indomita.", author: "Mahatma Gandhi" },
  { id: 21, text: "Non importa quanto lentamente vai, purché tu non ti fermi.", author: "Confucio" },
  { id: 22, text: "Il cambiamento non è mai doloroso. Solo la resistenza al cambiamento lo è.", author: "Buddha" },
  { id: 23, text: "Ogni esperto è stato una volta un principiante.", author: "Helen Hayes" },
  { id: 24, text: "La vera perdita è quando abbandoni i tuoi sogni per paura del fallimento.", author: "Anonimo" },
  { id: 25, text: "Ciò che non ti uccide ti rende più forte.", author: "Friedrich Nietzsche" },
  { id: 26, text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
  { id: 27, text: "Non avere paura di crescere lentamente. Abbi paura di restare fermo.", author: "Proverbio cinese" },
  { id: 28, text: "Il corpo ottiene ciò che la mente crede.", author: "Anonimo" },
  { id: 29, text: "Ogni fallimento è un passo verso il successo.", author: "Anonimo" },
  { id: 30, text: "La differenza tra chi riesce e chi non riesce è come usa il tempo libero.", author: "Anonimo" },
  { id: 31, text: "Non aspettare condizioni ideali. Inizia ora, migliora man mano.", author: "Anonimo" },
  { id: 32, text: "Sii la causa del tuo successo, non la vittima delle tue circostanze.", author: "Anonimo" },
  { id: 33, text: "La mente è tutto. Ciò che pensi, diventi.", author: "Buddha" },
  { id: 34, text: "Ogni giorno è una nuova opportunità per cambiare la tua vita.", author: "Anonimo" },
  { id: 35, text: "Non misurare i tuoi progressi con il metro degli altri.", author: "Anonimo" },
  { id: 36, text: "Il coraggio non è assenza di paura, ma decidere che qualcos'altro è più importante.", author: "Ambrose Redmoon" },
  { id: 37, text: "Vinci nella tua mente prima di vincere nella tua vita.", author: "Anonimo" },
  { id: 38, text: "La coerenza batte il talento quando il talento non è coerente.", author: "Anonimo" },
  { id: 39, text: "Non sono i giorni della tua vita che contano, ma la vita nei tuoi giorni.", author: "Abraham Lincoln" },
  { id: 40, text: "Il tuo futuro è creato da ciò che fai oggi, non domani.", author: "Robert Kiyosaki" },
  { id: 41, text: "Sii qualcuno che si alza quando cade, non qualcuno che non cade mai.", author: "Anonimo" },
  { id: 42, text: "La vita comincia alla fine della tua zona di comfort.", author: "Neale Donald Walsch" },
  { id: 43, text: "Non aspettare l'ispirazione. Agisci e l'ispirazione seguirà.", author: "Anonimo" },
  { id: 44, text: "Ogni mattina che ti svegli hai un'altra possibilità.", author: "Anonimo" },
  { id: 45, text: "Il più grande ostacolo al tuo successo sei tu stesso.", author: "Anonimo" },
  { id: 46, text: "Non si può tornare indietro e cambiare l'inizio, ma si può ricominciare e cambiare il finale.", author: "C.S. Lewis" },
  { id: 47, text: "Smetti di aspettare e inizia a creare.", author: "Anonimo" },
  { id: 48, text: "Il cambiamento inizia quando decidi di non accettare più lo status quo.", author: "Anonimo" },
  { id: 49, text: "Sii così bravo che non possano ignorarti.", author: "Steve Martin" },
  { id: 50, text: "Il successo non è misurato da ciò che realizzi, ma dagli ostacoli che superi.", author: "Booker T. Washington" },
  { id: 51, text: "Ogni piccola azione conta. Non sottovalutare il potere dei piccoli passi.", author: "Anonimo" },
  { id: 52, text: "Il talento è comune. La dedizione è rara.", author: "Anonimo" },
  { id: 53, text: "Non cercare la perfezione. Cerca il progresso.", author: "Anonimo" },
  { id: 54, text: "La forza cresce nella sfida e si affievolisce nel comfort.", author: "Anonimo" },
  { id: 55, text: "Fai in modo che ogni giorno conti.", author: "Anonimo" },
  { id: 56, text: "Il dolore è temporaneo. Il rimpianto è per sempre.", author: "Anonimo" },
  { id: 57, text: "Non è mai troppo tardi per diventare ciò che avresti potuto essere.", author: "George Eliot" },
  { id: 58, text: "La tua vita non migliora per caso. Migliora per cambiamento.", author: "Jim Rohn" },
  { id: 59, text: "Il successo è andare da un fallimento all'altro senza perdere l'entusiasmo.", author: "Winston Churchill" },
  { id: 60, text: "Non lasciare che le tue paure siano più grandi dei tuoi sogni.", author: "Anonimo" },
  { id: 61, text: "Costruisci abitudini che costruiscono te.", author: "Anonimo" },
  { id: 62, text: "La disciplina è scegliere tra ciò che vuoi ora e ciò che vuoi di più.", author: "Abraham Lincoln" },
  { id: 63, text: "Un anno da oggi desidererai di aver iniziato oggi.", author: "Karen Lamb" },
  { id: 64, text: "Non è la montagna che dobbiamo conquistare, ma noi stessi.", author: "Edmund Hillary" },
  { id: 65, text: "Il progresso richiede tempo. Non arrenderti prima che accada.", author: "Anonimo" },
  { id: 66, text: "Sii paziente con te stesso. Niente in natura fiorisce tutto l'anno.", author: "Anonimo" },
  { id: 67, text: "La versione migliore di te ti sta aspettando dall'altra parte della paura.", author: "Anonimo" },
  { id: 68, text: "Non essere spaventato di essere bravo in qualcosa. Sii spaventato di non provarci.", author: "Anonimo" },
  { id: 69, text: "Ogni giorno ti avvicini o ti allontani da dove vuoi essere.", author: "Anonimo" },
  { id: 70, text: "Il tuo limite sei solo tu.", author: "Anonimo" },
  { id: 71, text: "Non rimandare. Il momento migliore per piantare un albero era vent'anni fa. Il secondo momento migliore è adesso.", author: "Proverbio cinese" },
  { id: 72, text: "Agisci come se ciò che fai facesse la differenza. Lo fa.", author: "William James" },
  { id: 73, text: "Le persone di successo fanno ciò che le persone di insuccesso non vogliono fare.", author: "Anonimo" },
  { id: 74, text: "La chiarezza porta motivazione. L'azione porta risultati.", author: "Anonimo" },
  { id: 75, text: "Non aspettare che qualcuno ti dia il permesso di vivere al massimo.", author: "Anonimo" },
  { id: 76, text: "Il tuo impegno di oggi è il tuo successo di domani.", author: "Anonimo" },
  { id: 77, text: "Smetti di lamentarti e inizia ad allenarsi.", author: "Anonimo" },
  { id: 78, text: "L'unico modo per fare un ottimo lavoro è amare ciò che fai.", author: "Steve Jobs" },
  { id: 79, text: "Non puoi sempre controllare ciò che accade, ma puoi controllare come reagisci.", author: "Anonimo" },
  { id: 80, text: "Il successo appartiene a chi non smette di provare.", author: "Anonimo" },
  { id: 81, text: "Ogni mattina hai la possibilità di essere migliore di ieri.", author: "Anonimo" },
  { id: 82, text: "Non confrontare il tuo capitolo 1 con il capitolo 20 di qualcun altro.", author: "Anonimo" },
  { id: 83, text: "La resilienza non è tornare a come eri. È diventare più forte di prima.", author: "Anonimo" },
  { id: 84, text: "Investi in te stesso. È il miglior investimento che puoi fare.", author: "Anonimo" },
  { id: 85, text: "Non lasciare che chi si è arreso ti convinca ad arrenderti.", author: "Anonimo" },
  { id: 86, text: "La grandezza non è data. È costruita mattone dopo mattone.", author: "Anonimo" },
  { id: 87, text: "Sii la persona che il tuo cane pensa tu sia.", author: "Anonimo" },
  { id: 88, text: "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.", author: "Eleanor Roosevelt" },
  { id: 89, text: "Non aspettare la tempesta che passi. Impara a ballare sotto la pioggia.", author: "Anonimo" },
  { id: 90, text: "Ogni giorno è un'opportunità per essere migliore di ieri.", author: "Anonimo" },
  { id: 91, text: "La perseveranza è fallire diciannove volte e riuscire alla ventesima.", author: "Julie Andrews" },
  { id: 92, text: "Non esistono scorciatoie per un luogo che vale la pena visitare.", author: "Beverly Sills" },
  { id: 93, text: "Il tuo atteggiamento determina la tua direzione.", author: "Anonimo" },
  { id: 94, text: "Inizia dove sei. Usa ciò che hai. Fai ciò che puoi.", author: "Arthur Ashe" },
  { id: 95, text: "Non è mai troppo tardi per essere ciò che vorresti essere.", author: "Anonimo" },
  { id: 96, text: "La coerenza è la madre di tutte le virtù.", author: "Anonimo" },
  { id: 97, text: "Fai ogni giorno qualcosa che ti spaventa un po'.", author: "Eleanor Roosevelt" },
  { id: 98, text: "Il successo è costruito su un pilastro di tentativi falliti.", author: "Anonimo" },
  { id: 99, text: "Non aspettare che le condizioni siano perfette. Inizia e migliorale.", author: "Anonimo" },
  { id: 100, text: "Chi non risica non rosica. Ma chi risica troppo rosica tutto.", author: "Proverbio italiano" },
  { id: 101, text: "Il modo migliore per predire il futuro è crearlo.", author: "Peter Drucker" },
  { id: 102, text: "Non si tratta di essere il migliore. Si tratta di essere migliore di ieri.", author: "Anonimo" },
  { id: 103, text: "La vita è troppo corta per vivere quella degli altri.", author: "Anonimo" },
  { id: 104, text: "Non lasciare che il rumore delle opinioni altrui zittisca la tua voce interiore.", author: "Steve Jobs" },
  { id: 105, text: "Ogni ostacolo è un'opportunità in disguise.", author: "Anonimo" },
  { id: 106, text: "La mente che si apre a una nuova idea non torna mai alla dimensione originale.", author: "Albert Einstein" },
  { id: 107, text: "Non rimpiangere ciò che non hai fatto. Fallo adesso.", author: "Anonimo" },
  { id: 108, text: "La forza non viene dal vincere. Viene dalla lotta.", author: "Arnold Schwarzenegger" },
  { id: 109, text: "Ogni expert è stato un principiante che non si è arreso.", author: "Anonimo" },
  { id: 110, text: "Il tuo corpo può sopportare quasi tutto. È la tua mente che devi convincere.", author: "Anonimo" },
  { id: 111, text: "Non si cresce nella comfort zone.", author: "Anonimo" },
  { id: 112, text: "Fai di ogni giorno un capolavoro.", author: "John Wooden" },
  { id: 113, text: "Il successo è un viaggio, non una destinazione.", author: "Ben Sweetland" },
  { id: 114, text: "Non lasciare che le piccole cose rubino la tua felicità.", author: "Anonimo" },
  { id: 115, text: "La tua energia fluisce dove va la tua attenzione.", author: "Anonimo" },
  { id: 116, text: "Sii la versione di domani di te stesso già da oggi.", author: "Anonimo" },
  { id: 117, text: "Non aspettare la motivazione per agire. Agisci e la motivazione arriverà.", author: "Anonimo" },
  { id: 118, text: "Il cambiamento comincia con una decisione.", author: "Anonimo" },
  { id: 119, text: "Non sono le circostanze a fare l'uomo, ma l'uomo a fare le circostanze.", author: "Benjamin Disraeli" },
  { id: 120, text: "Ogni giorno che ti impegni è un giorno che non sprechi.", author: "Anonimo" },
]

export function getRandomQuote(quotes, dislikedIds, lastShownId) {
  const available = quotes.filter(q =>
    !dislikedIds.includes(q.id) && q.id !== lastShownId
  )
  if (available.length === 0) return quotes[0]
  return available[Math.floor(Math.random() * available.length)]
}
